### ISSUE TITLE
ImageNet的参数配置

### ISSUE THREAD

**Issue by silencelzx** [TreezzZ/HashNet_PyTorch#1]
你好！我对HashNet有兴趣，想复现一下在ImageNet的表现，但是我的计算资源有限，可以告诉我HashNet在ImageNet上的参数设置吗？

**Comment by TreezzZ** [comment]
> 你好！我对HashNet有兴趣，想复现一下在ImageNet的表现，但是我的计算资源有限，可以告诉我HashNet在ImageNet上的参数设置吗？

你好，使用默认参数即可，README里的结果是MAP@1000，如果你需要其他topk的结果，通过--topk xxx设置
